"""Auto-generated by `python -m vision.calibrate --profile sim` (SS3.5
step 3) -- DO NOT EDIT BY HAND, re-run calibrate.py instead. One set of
soft-limit numbers shared by firmware and Python (ORCHESTRATION.md SS3.5:
"provisions the ESP32's enforced limits -- one set of numbers").

Deploy alongside main.py (see firmware/README.md):
    mpremote cp profiles/sim/firmware_limits.py :firmware_limits.py

firmware/main.py imports this module (flat, at the board root) and falls
back to shared/serial_protocol.py's bench-safe defaults if it is absent.
"""

PAN_MIN = -90.0
PAN_MAX = 90.0
TILT_MIN = -45.0
TILT_MAX = 45.0
